baseURL = 'https://aradaelli.com/'
languageCode = 'en-us'
title = 'Andrea Radaelli'
enableRobotsTXT = true
markup.highlight.noClasses = false

[minify]
  disableXML = true

[outputs]
  home = ['HTML']
  section = ['HTML', 'RSS']